import Link from 'next/link';
import SanskritNav from '../SanskritNav';

export default function SanskritCollaborate(){return <>
  <section className="pageHero localizedHero sanskritHero"><div className="languageHeroInner"><div className="eyebrow">विद्वत्ता • पद्धतिः • संयुक्तजिज्ञासा</div><h1>आइवीपण्डितेन सह सहकारः</h1><p>संस्कृत-शास्त्रविद्वत्तां आधुनिकविज्ञान-चिकित्सा-मानविकी-अनुसन्धानसंरचनाभिः सह प्रत्यक्षसंवादे स्थापयितुं आइवीपण्डितः गम्भीरसहकार्यं अन्विष्यति।</p></div></section>
  <main className="content devanagariPage sanskritPage"><SanskritNav/>
    <section className="collabIntro panel"><h2>भवान्/भवती विशेषज्ञतां आनयतु; प्रश्नं वयं संयुक्ततया निर्मामः।</h2><p>भवतः समीपे मनः, भाषा, स्वास्थ्यं, व्यवहारः, चेतना, मानवकल्याणं, विचारइतिहासः वा विषयीकृत्य प्रश्नं प्रकाशयितुं शक्नुवन् संस्कृतपाठः, संकल्पना, साधना, भाष्यपरम्परा, अल्पाधीतग्रन्थसमूहः वा अस्ति किम्? अथवा भवान् वैज्ञानिकः अस्ति, यः पारम्परिकसामग्रीणां सतहीपठनं निवारयितुं विदुषां सहयोगं इच्छति किम्?</p><p className="quoteBlock">सहकारस्य आरम्भः मूलस्रोतस्य अवबोधेन — पूर्वनिर्धारितवैज्ञानिकदावस्य सिद्ध्या न।</p></section>
    <section className="audienceGrid"><article><span>संस्कृतविद्वांसः</span><h3>मूलस्रोतः परम्परा च</h3><p>प्राथमिकस्रोतांसि चिनोतु, पाठसन्दर्भं स्थापयतु, शाळा-भाष्यपरम्पराभेदान् विवेचयतु, पदावलीं परिष्करोतु, प्रस्तावितवैज्ञानिकानुवादः उत्तरदायी अस्ति वा न इति निर्णेतुं सहयोगं कुर्वन्तु।</p></article><article><span>विज्ञानिनः चिकित्सकाश्च</span><h3>परीक्षणं पद्धतिश्च</h3><p>कः प्रश्नः मापनीयः, के controls आवश्यकाः, प्रमाणस्य स्तरः कथं निश्चितव्यः, आधुनिकपदावली कुत्र मूलार्थं विकृतं करोति इति निर्णये सहयोगं कुर्वन्तु।</p></article><article><span>संस्थाः समर्थकाश्च</span><h3>भारते अनुसन्धानसंरचना</h3><p>अन्तरविषयकदलानि, कार्यशालाः, pilot-संरचना, fellowships, datasets, स्पर्धात्मकप्रस्तावाश्च निर्मातुं सहयोगं कुर्वन्तु।</p></article></section>
    <section className="panel"><p className="kicker">सम्भावितफलितानि</p><h2>प्रत्येकः संवादः अनुदानप्रस्तावेन आरब्धव्यः न।</h2><div className="outcomeCloud"><span>पाठाध्ययनम्</span><span>आलोचनात्मकग्रन्थसूची</span><span>शब्दकोशाः</span><span>pilot-प्रयोगाः</span><span>डिजिटल-corpora</span><span>अनुसन्धानप्रश्नाः</span><span>कार्यशालाः</span><span>datasets</span><span>बहुकेन्द्रीयजालानि</span><span>अनुदानप्रस्तावाः</span><span>सार्वजनिकव्याख्यानानि</span><span>विद्वत्प्रकाशनानि</span></div></section>
    <section className="contactInvitation"><div><p className="kicker">लघुसन्देशेन आरम्भः</p><h2>भवान्/भवती किं जानाति? कः प्रश्नः जिज्ञासां जनयति? किं अध्ययनयोग्यम्?</h2><p>केचन विचारपूर्णाः अनुच्छेदाः पर्याप्ताः। सम्भवति चेत् सम्बन्धितग्रन्थं, परम्परां, वैज्ञानिकसमस्यां, संस्थागतावसरं वा उल्लिखतु।</p></div><div className="contactActions"><a className="btn primary" href="mailto:nishant.mishra@ivypandit.com?cc=nishmishra@gmail.com&subject=IvyPandit%20Sanskrit%20Collaboration">ईमेल् प्रेषयतु</a><Link className="btn secondary" href="/sa/prashna">प्रश्नान् पश्यतु</Link></div></section>
  </main>
</>}
