export default function Articles(){return <>
  <section className="pageHero"><div className="eyebrow">Definitive guides • Scholarly essays • Evidence-aware inquiry</div><h1>Articles</h1><p>Canonical, source-conscious articles connecting Indian Knowledge Systems, neuroscience, learning, culture, health, and public scholarship.</p></section>
  <main className="content">
    <section className="callout" style={{marginBottom:'28px'}}><span className="label">FEATURED SCHOLARLY ESSAY</span><h2>From Puruṣa to Viśvarūpa to Govinda</h2><p>Why the Infinite Divine is worshipped through sacred forms—a respectful reading of the Puruṣa Sūkta, Bhagavad Gītā Chapters 10–11, and <i>Bhaja Govindam</i>.</p><a className="textLink" href="/articles/purusha-sukta-gita-vedic-cosmos">Read in English →</a><br/><a className="textLink" href="/hi/articles/purusha-sukta-gita-vedic-cosmos">हिन्दी में पढ़ें →</a></section>
    <div className="resourceGrid">
      <div className="panel"><span className="label">DEFINITIVE GUIDE</span><h3>Avadhāna and the Indian Science of Attention</h3><p>A comprehensive framework for Avadhāna, attention, working memory, cognitive expertise, neuroplasticity, and future research.</p><a className="textLink" href="/research/consciousness/avadhana">Read →</a></div>
      <div className="panel"><span className="label">CONTEMPLATIVE SCIENCE</span><h3>From Ritual to Mechanism: Sandhyopāsanā</h3><p>Mantra, breath, attention, meaning, imagery, timing, and daily discipline.</p><a className="textLink" href="/articles/sandhyopasana-neuroscience">Read →</a></div>
      <div className="panel"><span className="label">LANGUAGE & DEVELOPMENT</span><h3>Vedic Recitation and the Developing Brain</h3><p>Oral training, memory, auditory–motor learning, attention, and neuroplasticity.</p><a className="textLink" href="/articles/vedic-recitation-developing-brain">Read →</a></div>
      <div className="panel"><span className="label">BILINGUALISM</span><h3>Sanskrit–Hindi Bilingualism & Neuroplasticity</h3><p>Language experience, shared script, cognitive control, and evidence beyond the bilingual-advantage debate.</p><a className="textLink" href="/articles/sanskrit-hindi-bilingualism-neuroplasticity">Read →</a></div>
      <div className="panel"><span className="label">FOUNDATIONAL METHOD</span><h3>From Śāstra to Scientific Discovery</h3><p>A six-step pathway from primary source and interpretation to question, evidence, and responsible return.</p><a className="textLink" href="/articles/shastra-to-scientific-discovery">Read →</a></div>
      <div className="panel"><span className="label">MEMORY & CULTURE</span><h3>Pitṛpakṣa, Memory, Grief & Identity</h3><p>Ancestral remembrance alongside careful scientific questions about grief, ritual, narrative, and family identity.</p><a className="textLink" href="/articles/pitrapaksha-memory-grief">Read →</a></div>
      <div className="panel"><span className="label">EVIDENCE REVIEW</span><h3>Ekādaśī Fasting, Metabolism & Brain Health</h3><p>What intermittent-fasting evidence can—and cannot—tell us about a diverse devotional practice.</p><a className="textLink" href="/articles/ekadashi-fasting-brain-health">Read →</a></div>
      <div className="panel"><span className="label">SCHOLARLY ESSAY</span><h3>Gāyatrī & Neuroplasticity</h3><p>Attention, repetition, meaning, development, and the limits of current scientific evidence.</p><a className="textLink" href="/articles/gayatri-neuroplasticity">Read →</a></div>
      <div className="panel"><span className="label">REFLECTION</span><h3>Gītā & Cognitive Resilience</h3><p>Arjuna’s crisis, disciplined action, and responsible comparison with modern psychology.</p><a className="textLink" href="/articles/gita-cognitive-resilience">Read →</a></div>
      <div className="panel"><span className="label">PRECONCEPTION HEALTH</span><h3>Garbhādhāna & Epigenetics</h3><p>Parental preparation, preconception health, and responsible limits on epigenetic analogy.</p><a className="textLink" href="/articles/garbhadhana-epigenetics">Read →</a></div>
    </div>
    <section className="callout" style={{marginTop:'28px'}}><b>Editorial note:</b> traditional meaning, interpretation, research hypothesis, and scientific evidence are identified separately. Articles are revised as scholarship develops. <a className="textLink" href="/editorial-policy">Read the editorial policy →</a></section>
  </main>
</>}
